spring.application.name=learningplatform
spring.data.mongodb.uri=mongodb://localhost:27017/spring_auth_db

server.tomcat.relaxed-cookies=true


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sbblearningauthor@gmail.com
spring.mail.password=nxoj fzzb uwfs wuyn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.debug=true

razorpay.key_id=AC08a324ebbcd15943a4663c041f34dc0f
razorpay.key_secret=AC08a324ebbcd15943a4663c041f34dc0f

server.servlet.session.persistent=false

